### ISSUE TITLE
Error in HA logs: "No 'version' key in the manifest file for custom integration 'momentary'"

### ISSUE THREAD

**Issue by sphanley** [twrecked/hass-momentary#12]
When the latest version of Home Assistant is starting up with the 0.5 release of the Momentary integration installed, I see the following error in the logs, indicating an issue which needs to be resolved before it becomes breaking:

> Logger: homeassistant.loader
> Source: loader.py:802
> First occurred: 6:00:42 PM (1 occurrences)
> Last logged: 6:00:42 PM
> 
> No 'version' key in the manifest file for custom integration 'momentary'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'momentary'

**Comment by twrecked** [comment]
Should be fixed in [0.5.1](https://github.com/twrecked/hass-momentary/releases/tag/v0.5.1).

**Comment by twrecked** [comment]
Closing because fixed.
