### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by tomlut** [twrecked/hass-momentary#2]
What does the push button look like in the frontend?

**Comment by twrecked** [comment]
It looks just like any other switch. You can configure the icon as you see fit.

**Comment by tomlut** [comment]
That's not a helpful answer.

**Comment by twrecked** [comment]
It looks like the `triggers` switches in this screen shot:

![momentary](https://user-images.githubusercontent.com/47094394/72192206-cc2ef680-33d2-11ea-9f60-ff8d5f726bb4.png)

**Comment by tomlut** [comment]
Thanks.

**Comment by twrecked** [comment]
No worries. It doesn't work well in a glance card, it keeps opening up the state window. It works well as an entity button but it's way too big.

I might get around to a fancy new lovelace device one day, I just don't have the time now.

![momentary2](https://user-images.githubusercontent.com/47094394/72192612-66436e80-33d4-11ea-8355-505ee55e5604.png)
