### ISSUE TITLE
toggle_for not working after upgrade

### ISSUE THREAD

**Issue by sreggy** [twrecked/hass-momentary#22]
I did upgrade to version v0.6.1.1, after that toggle_for was not working.

Following my configuration
- platform: momentary
  name: Allow Unlock
  mode: on
  toggle_for: 30

switch stay 'off' for no more tha 1s intead of 30sec.

I'm running HA as docker on Raspberry PI 4, version is 2023.1.2.

Would you help me?

Thanks in advance
Regards
Stefano

**Comment by twrecked** [comment]
I'll take a look. Thanks for reporting.

**Comment by twrecked** [comment]
Can you try changing the mode to `off`.

**Comment by twrecked** [comment]
Sorry, I'm an idiot, I removed the wrong deprecated options. The latest version should work.

**Comment by sreggy** [comment]
Thanks a lot.

I did a check, reinstalled HACS repo v0.6.2 and everythings is working fine.

thanks again, 
regards
Stefano
