### ISSUE TITLE
Feature request: Keep state of switch and timer after HA restart

### ISSUE THREAD

**Issue by poudenes** [twrecked/hass-momentary#25]
Hi All,

I love this integration. Would be so nice to have option that the integration can check if there is a HA restart and before the restart switch was on and for how long. Then when HA run again keep state and go with the timer where its end because of restart.

Example:
switch 1 is on for total 7200 seconds. HA restart after 30min of turn on this switch.
When HA is restart, switch keep on and there is 5400 seconds left before it turns off.

**Comment by twrecked** [comment]
Should be available in #26
