### ISSUE TITLE
HACS and version 0.7

### ISSUE THREAD

**Issue by cirrusflyer** [twrecked/hass-momentary#36]
Is there a way to install version 0.7 using HACS?

**Comment by twrecked** [comment]
You need to turn on `Show beta versions`. 

Go to HACS, click the three dots to the right of Momentary and select `Redownload` and change the setting on that screen.

**Comment by cirrusflyer** [comment]
Thanks!  Do you recommend the 0.7 version at this point?  Stable enough?

**Comment by twrecked** [comment]
I think it, it's basically the old code but with a _config flow_ front end, i.e., you can look at the devices on the `Integrations` page.

If you don't remove your old config - just keep ignoring the warnings - you can even revert to 0.6 if you run into problems.
