### ISSUE TITLE
Feature request: Momentary OFF feature

### ISSUE THREAD

**Issue by wiiNinja** [twrecked/hass-momentary#4]
Similar to momentary ON, please allow an invert so that this can be used as momentary OFF. I would like to have a device ON all the time, but turned OFF for a couple of seconds only in emergency situations. Thank you.

**Comment by twrecked** [comment]
That should be possible, I can add a `mode` configuration. Leave it with me.

**Comment by wiiNinja** [comment]
Thanks for the swift response.

**Comment by twrecked** [comment]
I just merged this.

#5 

It's available as release v0.4. Let me know if it works.

**Comment by wiiNinja** [comment]
Exactly what I needed. Works perfectly. Thanks.

**Comment by twrecked** [comment]
Excellent.
