### ISSUE TITLE
Momentry failing to run.

### ISSUE THREAD

**Issue by Outsidewall** [twrecked/hass-momentary#40]
Hello,

Just installed momentary, sadly I get the following error
Logger: homeassistant.setup
Source: setup.py:404
First occurred: 8:59:52 AM (1 occurrences)
Last logged: 8:59:52 AM

Error during setup of component momentary
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/momentary/__init__.py", line 45, in async_setup
    data=config[Platform.SWITCH]
         ~~~~~~^^^^^^^^^^^^^^^^^
KeyError: <Platform.SWITCH: 'switch'>

Any thoughts?

John

**Comment by twrecked** [comment]
Which version?

And can you post your config.

**Comment by Outsidewall** [comment]
verison __version__ = "0.7.0b8" from __init__.py

momentary.yaml
version: 1
switches:
- name: Momentary Test

**Comment by twrecked** [comment]
The file looks fine.

Was this an upgrade? Because that is in the upgrade code.

If not, did you get the filename wrong?

**Comment by Outsidewall** [comment]
It was a new install, git clone, copy across to the the custom dir... nothing clever. HA running in docker container.

**Comment by Outsidewall** [comment]
# sum *
04710    15 cfg.py
06867     4 config_flow.py
48689     1 const.py
21200     5 __init__.py
29711     1 manifest.json
sum: __pycache__: Is a directory
44453     8 switch.py
sum: translations: Is a directory

Tried removing pycahe dir, docker restart, still the same.

**Comment by twrecked** [comment]
I think this is a configuration my code isn't handling correctly. 

Do you have any switches defined in your current config?

**Comment by Outsidewall** [comment]
Just one setup in the momentary.yaml, as per my post above

I have some virtuals setup, using your virtual plugin, see below, plus a node red one

virtual.yaml
version: 1
devices:
  Occupied:
   - platform: switch
     name: Occupied
     persistent: True
     initial_value: on
  Night Mode:
   - platform: binary_sensor
     name: Night Test
     initial_value: 'off'
     class: door
  Night Switch:
   - platform: switch
     name: Night Switch
     initial_value: 'off'
     class: door
  BedLeds:
   - platform: switch
     name: Bed Leds
     persistent: True
     initial_value: off

**Comment by twrecked** [comment]
I think I know what this is and I'll push a fix later. The code (and me I guess) assume everyone has a `switch` entry in `configuration.yaml`.

I'll fix it to fail in a better way.

**Comment by Outsidewall** [comment]
Cool, look forward to the fix

**Comment by twrecked** [comment]
It should be fixed in 0.7.0b8 by #41 

I think the issue was you had `momentary:` in your `configuration.yaml` but no `switch:` entry. I think. Either way the fix should work for you.

**Comment by Outsidewall** [comment]
Install, tested, working, thank you
