### ISSUE TITLE
SwitchDevice is deprecated, modify MomentarySwitch to extend SwitchEntity

### ISSUE THREAD

**Issue by netfriend85** [twrecked/hass-momentary#9]
Hello,
Thank you for the Momentary Switch component. 

I am running 0.116.4 and recently noticed the following 'warning' entry: "SwitchDevice is deprecated, modify MomentarySwitch to extend SwitchEntity"
Has this been observed by others? Can you advice how to fix this?

Regards,

**Comment by twrecked** [comment]
Upgrade to version 0.5, it should fix the issue.

**Comment by netfriend85** [comment]
That did it.
I have missed to see that there was v0.5. 
 
Thanks for the quick reply.
